spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hris
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: false
server:
  servlet:
    context-path: /api